[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "tdmg"
version = "0.1.0"
description = "Trainiere dein musikalisches Gehör"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "sounddevice",
]

license = "GPL-3.0"
authors = [
    { name = "Martin Lehmann" },
]

[project.scripts]
tdmg = "main:main"

[tool.setuptools]
py-modules = [
    "main",
    "gui",
    "variables",
    "const",
    "table",
    "overtones",
    "scale",
    "rhythm",
    "settings",
    "button_bar",
    "dialog",
    "end_window",
    "note",
    "random_matrix",
    "chord",
    "overtone_matrix",
    "overtone",
]

[project.urls]
Homepage = "https://mathemartin.de/programme.html"
Repository = "https://github.com/mathemartin/Trainiere-dein-musikalisches-Geh-r"

[project.optional-dependencies]
dev = [
    "ruff",
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

# soweit der python code ordentlich bereinigt wird, kann später auch …
# [tool.ruff.lint]
# select = [
    # "E",
    # "F",
    # "W",
# ]
